export const alertConstants = {
  SUCCESS: "ALERT_SUCCESS",
  ERROR: "ALERT_ERROR",
  SAVE: "ALERT_SAVE",
  CLEAR: "ALERT_CLEAR"
};

export const userConstants = {
  LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  LOGIN_FAILURE: "USER_LOGIN_FAILURE",

  GETROLE_REQUEST: "USER_GETROLE_REQUEST",
  GETROLE_SUCESS: "USER_GETROLE_SUCCESS",
  GETROLE_FAILURE: "USER_GETROLE_FAILURE",

  LOGOUT: "USER_LOGOUT",

  GETALL_REQUEST: "USERS_GETALL_REQUEST",
  GETALL_SUCCESS: "USERS_GETALL_SUCCESS",
  GETALL_FAILURE: "USERS_GETALL_FAILURE"
};

export const developmentFormConstants = {
  GETALL_REQUEST: "DEVELOPMENTFORMS_GETALL_REQUEST",
  GETALL_SUCCESS: "DEVELOPMENTFORMS_GETALL_SUCCESS",
  GETALL_FAILURE: "DEVELOPMENTFORMS_GETALL_FAILURE",

  GETALLCOMPETENCES_REQUEST: "COMPETENCES_GETALL_REQUEST",
  GETALLCOMPETENCES_SUCCESS: "COMPETENCES_GETALL_SUCCESS",
  GETALLCOMPETENCES_FAILURE: "COMPETENCES_GETALL_FAILURE",

  GETALLMAINCATEGORIES_REQUEST: "MAINCATEGORIES_GETALL_REQUEST",
  GETALLMAINCATEGORIES_SUCCESS: "MAINCATEGORIES_GETALL_SUCCESS",
  GETALLMAINCATEGORIES_FAILURE: "MAINCATEGORIES_GETALL_FAILURE",

  GETALLSUBCATEGORIES_REQUEST: "SUBCATEGORIES_GETALL_REQUEST",
  GETALLSUBCATEGORIES_SUCCESS: "SUBCATEGORIES_GETALL_SUCCESS",
  GETALLSUBCATEGORIES_FAILURE: "SUBCATEGORIES_GETALL_FAILURE",

  GETALLCRITERIA_REQUEST: "CRITERIA_GETALL_REQUEST",
  GETALLCRITERIA_SUCCESS: "CRITERIA_GETALL_SUCCESS",
  GETALLCRITERIA_FAILURE: "CRITERIA_GETALL_FAILURE",

  CREATEDEVELOPMENTSHEET_REQUEST: "CREATEDEVELOPMENTSHEET__REQUEST",
  CREATEDEVELOPMENTSHEET_SUCCESS: "CREATEDEVELOPMENTSHEET_SUCCESS",
  CREATEDEVELOPMENTSHEET_FAILURE: "CREATEDEVELOPMENTSHEET_FAILURE"
};

export const traineeDevelopmentFormConstants = {
  SETDEVSHEET_REQUEST: "SETDEVSHEET_REQUEST",
  SETDEVSHEET_SUCCESS: "SETDEVSHEET_SUCCESS",
  SETDEVSHEET_FAILURE: "SETDEVSHEET_FAILURE"
};

export const traineeTabConstants = {
  GETALL_REQUEST: "TRAINEES_GETALL_REQUEST",
  GETALL_SUCCESS: "TRAINEES_GETALL_SUCCESS",
  GETALL_FAILURE: "TRAINESS_GETALL_FAILURE"
};

export const trainerDevelopmentFormConstants = {
  SETDEVSHEET_REQUEST: "SETDEVSHEET_REQUEST",
  SETDEVSHEET_SUCCESS: "SETDEVSHEET_SUCCESS",
  SETDEVSHEET_FAILURE: "SETDEVSHEET_FAILURE",

  GETALL_CONNECTEDDEVSHEETS_REQUEST: "GETALL_CONNECTEDDEVSHEETS_REQUEST",
  GETALL_CONNECTEDDEVSHEETS_SUCCESS: "GETALL_CONNECTEDDEVSHEETS_SUCCESS",
  GETALL_CONNECTEDDEVSHEETS_FAILURE: "GETALL_CONNECTEDDEVSHEETS_FAILURE"
};
