export const alertConstants = {
  SUCCESS: "ALERT_SUCCESS",
  ERROR: "ALERT_ERROR",
  SAVE: "ALERT_SAVE",
  CLEAR: "ALERT_CLEAR"
};

export const userConstants = {
  LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  LOGIN_FAILURE: "USER_LOGIN_FAILURE",

  GETROLE_REQUEST: "USER_GETROLE_REQUEST",
  GETROLE_SUCESS: "USER_GETROLE_SUCCESS",
  GETROLE_FAILURE: "USER_GETROLE_FAILURE",

  LOGOUT: "USER_LOGOUT",

  GETALL_REQUEST: "USERS_GETALL_REQUEST",
  GETALL_SUCCESS: "USERS_GETALL_SUCCESS",
  GETALL_FAILURE: "USERS_GETALL_FAILURE"
};

export const developmentFormConstants = {
  GETALL_REQUEST: "DEVELOPMENTFORMS_GETALL_REQUEST",
  GETALL_SUCCESS: "DEVELOPMENTFORMS_GETALL_SUCCESS",
  GETALL_FAILURE: "DEVELOPMENTFORMS_GETALL_FAILURE",

  GETALLCOMPETENCES_REQUEST: "COMPETENCES_GETALL_REQUEST",
  GETALLCOMPETENCES_SUCCESS: "COMPETENCES_GETALL_SUCCESS",
  GETALLCOMPETENCES_FAILURE: "COMPETENCES_GETALL_FAILURE"
};
